//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minimarket
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDetalleVenta
    {
        public int Codigo { get; set; }
        public Nullable<int> CodigoVenta { get; set; }
        public Nullable<int> CodigoProducto { get; set; }
        public Nullable<decimal> PrecioUnidad { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<decimal> Descuento { get; set; }
    
        public virtual tblProducto tblProducto { get; set; }
        public virtual tblVenta tblVenta { get; set; }
    }
}
